version: '3'

services:
  site:
    build: ./site
    restart: always
    volumes:
      - ./site:/app
      - ./log:/app/log
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - ${DJANGO_PORT}:8000
    depends_on:
      mysql:
        condition: service_healthy

    env_file:
      - .env
    networks:
      - app-network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - ${NGINX_PORT}:80
      - 443:443
    depends_on:
      - site
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./log:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - app-network
  
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]


  celery:
    build: ./site
    command: celery -A core worker -l warning --logfile=/app/log/celery.log --concurrency=1
    volumes:
      - ./site:/app
      - ./log:/app/log
      - ./media:/app/media
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:


